# Generated by Django 5.0 on 2023-12-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='store_custo_last_na_0cc6d5_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customerss',
        ),
    ]
