# Generated by Django 5.0 on 2023-12-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0002_customer_store_custo_last_na_0cc6d5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_last_na_2e448d_idx',
            old_name='store_custo_last_na_0cc6d5_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
