# Generated by Django 5.0 on 2023-12-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0003_rename_store_custo_last_na_0cc6d5_idx_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """INSERT INTO thestore_collection (title) 
            VALUES('collection1')
    """,
            """DELETE FROM thestore_collection WHERE title=('collection1')"""
        )
    ]
