# Generated by Django 5.0 on 2023-12-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0004_auto_20231216_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membershib',
            field=models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1),
        ),
    ]
