# Generated by Django 5.0 on 2023-12-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0006_rename_birth_data_customer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membershib',
            new_name='membership',
        ),
    ]
